[project]
name = "diario-cli"
version = "1.0.2b1"
description = "Diario is an opinionated personal journaling tool inspired by bullet journal practices, based on plain UTF-8 Markdown files organized in a time-based directory structure. It prioritizes long-term readability, filesystem portability, and independence from the application itself."
authors = [
    {name = "Francesco Maida",email = "francesco.maida@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
]

[project.urls]
Homepage = "https://diario.cesco.it"
Repository = "https://github.com/fmaida/diario"

[tool.poetry]
packages = [
    {include = "diario", from = "src"},
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
diario = "diario.__main__:main"
